version: '3.9'

services:
  scraper:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped

    # volumes:
    #   - ./app:/app/app:ro